import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from typing import Dict, Any

def generate_startup_pdf(
    output_path: str,
    title: str,
    summary_data: Dict[str, Any],
    swot_data: Dict[str, Any],
    competitors: list,
    tech_stack: Dict[str, Any]
) -> str:
    """
    Generates a highly styled, corporate-grade PDF analysis report for a startup.
    Uses ReportLab flowables to ensure compatibility and dynamic size adjustments.
    """
    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Palette - Premium Navy & Teal
    primary_color = colors.HexColor("#0f172a") # Slate 900
    secondary_color = colors.HexColor("#0ea5e9") # Sky 500
    text_color = colors.HexColor("#334155") # Slate 700
    border_color = colors.HexColor("#e2e8f0") # Slate 200
    
    # Custom styles
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=32,
        leading=38,
        textColor=primary_color,
        alignment=0, # Left
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=secondary_color,
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'Header1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=primary_color,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10.5,
        leading=15,
        textColor=text_color,
        spaceAfter=10
    )
    
    th_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.white
    )
    
    td_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=text_color
    )
    
    story = []
    
    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 1.5 * inch))
    # Elegant Top Bar
    story.append(Table(
        [[Paragraph("", body_style)]],
        colWidths=[7 * inch],
        rowHeights=[4],
        style=TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), secondary_color),
        ])
    ))
    story.append(Spacer(1, 20))
    story.append(Paragraph(title.upper(), title_style))
    story.append(Paragraph("AI-POWERED VALIDATION & MARKET INTELLIGENCE REPORT", subtitle_style))
    story.append(Spacer(1, 20))
    
    meta_data = [
        [Paragraph("<b>Prepared For:</b> Investor & Founder Review", body_style)],
        [Paragraph("<b>Generated By:</b> StartupSense AI SaaS Platform", body_style)],
        [Paragraph("<b>Security Classification:</b> Private & Confidential", body_style)],
    ]
    meta_table = Table(meta_data, colWidths=[5 * inch])
    meta_table.setStyle(TableStyle([
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(meta_table)
    
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("<i>This report contains predictive machine learning insights, live competitive analyses, and strategic recommendations generated based on current market dynamics.</i>", body_style))
    story.append(PageBreak())
    
    # ------------------ SECTION 1: EXECUTIVE SUMMARY ------------------
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(summary_data.get("summary", ""), body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("<b>Core Problem Statement:</b>", body_style))
    story.append(Paragraph(summary_data.get("problem_statement", ""), body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("<b>Proposed Solution:</b>", body_style))
    story.append(Paragraph(summary_data.get("solution", ""), body_style))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("<b>Target Customer Audience:</b>", body_style))
    story.append(Paragraph(summary_data.get("target_audience", ""), body_style))
    story.append(Spacer(1, 20))
    
    # ------------------ SECTION 2: SWOT ANALYSIS ------------------
    story.append(Paragraph("2. Strategic SWOT Analysis", h1_style))
    
    # Make a clean 2x2 SWOT grid table
    swot_table_data = [
        [
            Paragraph("<b>STRENGTHS</b><br/>" + "<br/>".join([f"• {s}" for s in swot_data.get("strengths", [])]), td_style),
            Paragraph("<b>WEAKNESSES</b><br/>" + "<br/>".join([f"• {w}" for w in swot_data.get("weaknesses", [])]), td_style)
        ],
        [
            Paragraph("<b>OPPORTUNITIES</b><br/>" + "<br/>".join([f"• {o}" for o in swot_data.get("opportunities", [])]), td_style),
            Paragraph("<b>THREATS</b><br/>" + "<br/>".join([f"• {t}" for t in swot_data.get("threats", [])]), td_style)
        ]
    ]
    swot_table = Table(swot_table_data, colWidths=[3.5 * inch, 3.5 * inch])
    swot_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 1, border_color),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ('BACKGROUND', (0,0), (0,0), colors.HexColor("#f0fdf4")),  # light green
        ('BACKGROUND', (1,0), (1,0), colors.HexColor("#fef2f2")),  # light red
        ('BACKGROUND', (0,1), (0,1), colors.HexColor("#f0f9ff")),  # light blue
        ('BACKGROUND', (1,1), (1,1), colors.HexColor("#fffbeb")),  # light amber
    ]))
    story.append(swot_table)
    story.append(PageBreak())
    
    # ------------------ SECTION 3: COMPETITIVE LANDSCAPE ------------------
    story.append(Paragraph("3. Competitor Analysis", h1_style))
    story.append(Paragraph("Real-time competitor metrics tracked through active intelligence search:", body_style))
    story.append(Spacer(1, 10))
    
    comp_headers = [Paragraph("Competitor Name", th_style), Paragraph("Similarity", th_style), Paragraph("Core Moat/Strengths", th_style), Paragraph("Market Share", th_style)]
    comp_rows = [comp_headers]
    for comp in competitors:
        comp_rows.append([
            Paragraph(comp.get("name", ""), td_style),
            Paragraph(f"{comp.get('similarity_score', 0)}%", td_style),
            Paragraph(", ".join(comp.get("strengths", [])), td_style),
            Paragraph(comp.get("market_share", "Emerging"), td_style)
        ])
        
    comp_table = Table(comp_rows, colWidths=[1.8 * inch, 1.0 * inch, 3.0 * inch, 1.2 * inch])
    comp_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), primary_color),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
    ]))
    story.append(comp_table)
    story.append(Spacer(1, 20))
    
    # ------------------ SECTION 4: TECH STACK ------------------
    story.append(Paragraph("4. Recommended Technical Architecture", h1_style))
    
    tech_data = [
        [Paragraph("<b>Frontend Framework:</b>", td_style), Paragraph(tech_stack.get("frontend", "React 19, TypeScript, Tailwind CSS"), td_style)],
        [Paragraph("<b>Backend Engine:</b>", td_style), Paragraph(tech_stack.get("backend", "FastAPI (Python), Uvicorn"), td_style)],
        [Paragraph("<b>Database Layer:</b>", td_style), Paragraph(tech_stack.get("database", "PostgreSQL, SQLAlchemy ORM"), td_style)],
        [Paragraph("<b>AI/ML Services:</b>", td_style), Paragraph(tech_stack.get("ai_ml", "Gemini API, Scikit-Learn, Prophet"), td_style)],
    ]
    tech_table = Table(tech_data, colWidths=[2.2 * inch, 4.8 * inch])
    tech_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, border_color),
    ]))
    story.append(tech_table)
    
    doc.build(story)
    return output_path
